[package]
name = "ozra"
version = "0.0.3"
edition = "2024"
description = "OZRA - OZReport Analyzer, Rust API client for OZReport (unofficial)"
keywords = ["ozreport", "scraping", "parser"]
authors = ["Hyomin Koo <me@eatsteak.dev>"]
license = "MIT"
repository = "https://github.com/EATSTEAK/ozra"
readme = "README.md"

[features]
default = ["client", "gzip"]
client = ["dep:reqwest", "dep:tokio", "dep:urlencoding"]
gzip = ["dep:flate2"]
client-rustls = ["client", "reqwest/rustls"]
client-rustls-no-provider = ["client", "reqwest/rustls-no-provider"]

[dependencies]
thiserror = "2"
cesu8 = "1"
flate2 = { version = "1", optional = true }
urlencoding = { version = "2", optional = true }
reqwest = { version = "0.13.2", features = [
  "cookies",
], default-features = false, optional = true }
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "time",
], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[example]]
name = "fetch_abeek"
required-features = ["client"]
